-- CREATE SEQUENCE gpslog_id_seq;

CREATE TABLE gpslog (
    id INTEGER PRIMARY KEY, -- DEFAULT NEXTVAL ('gpslog_id_seq')
    lat DOUBLE PRECISION NOT NULL,
    lon DOUBLE PRECISION NOT NULL,
    ts TIMESTAMPTZ NOT NULL
);
