ALTER TABLE gpslog ADD tid VARCHAR DEFAULT 'pi' NOT NULL;
ALTER TABLE gpslog ADD velocity SMALLINT; -- USMALLINT
ALTER TABLE gpslog ADD alt SMALLINT; -- USMALLINT
ALTER TABLE gpslog ADD accuracy INTEGER; -- UINTEGER
ALTER TABLE gpslog ADD v_accuracy SMALLINT;
ALTER TABLE gpslog ADD batt_level SMALLINT; -- UTINYINT
ALTER TABLE gpslog ADD batt_status SMALLINT NOT NULL DEFAULT -1; -- UTINYINT
ALTER TABLE gpslog ADD cog SMALLINT; -- TINYINT
ALTER TABLE gpslog ADD rad INTEGER; -- UINTEGER
ALTER TABLE gpslog ADD trigger CHAR;
ALTER TABLE gpslog ADD pressure REAL;
ALTER TABLE gpslog ADD poi VARCHAR;
ALTER TABLE gpslog ADD conn_status CHAR;
ALTER TABLE gpslog ADD tag VARCHAR;
ALTER TABLE gpslog ADD topic VARCHAR;
ALTER TABLE gpslog ADD inregions TEXT;
ALTER TABLE gpslog ADD inrids TEXT;
ALTER TABLE gpslog ADD ssid VARCHAR;
ALTER TABLE gpslog ADD bssid VARCHAR;
ALTER TABLE gpslog ADD created_at TIMESTAMPTZ;
ALTER TABLE gpslog ADD mmode SMALLINT; -- UTINYINT
-- ALTER TABLE gpslog ADD msg_id VARCHAR NOT NULL;
;
